### ISSUE TITLE
Broken link to blast+ rpm

### ISSUE THREAD

**Issue by ijpulidos** [dellacortelab/prospr#9]
In the `Dockerfile` we can see that there's a link to the ncbi blast rpm as follows:

`ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.9.0+-1.x86_64.rpm`

But that isn't working anymore, since latest version is 2.10.0, so I guess a solution is that we either change that to

`ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.10.0+-4.x86_64.rpm`

which is the current latest version, or manually linked to a specific version (which doesn't need to be the latest one) such that it won't be broken once the latest version changes, for example as follows, for version 2.9.0

`ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-1.x86_64.rpm`

**Comment by tyggna** [comment]
Thank you, I'm updating the Dockerfile now, we'll lock it to version 2.9.0 for the time being.  We're also planning a major re-release of this to make the container smaller and we're swapping out some unstable libraries for something a bit better suited.  This issue is resolved locally, so just wait until our next major push and this should be fixed.
